/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lRHltAJnMu3
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

export function Landing() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-white">
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 bg-gradient-to-r from-sky-200 to-sky-300">
          <div className="container px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem] text-primary-foreground">
                  Hola! Soy Budy
                </h1>
                <h2 className="text-lg text-primary-foreground mt-2">
                  Un simpático perro interactivo que está aquí para ayudarte a cuidar tu salud de manera fácil y segura.
                </h2>
                <p className="mx-auto max-w-[700px] text-primary-foreground md:text-lg">
                  Solo tienes que decirle cómo te sientes. Gracias a la inteligencia artificial y la tecnología
                  blockchain, toda la información que compartes con Budy es completamente privada y segura, tienes el
                  control total de tu salud sin preocupaciones.
                </p>
                <div className="space-x-4 mt-6">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Empezar
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Más información
                  </Link>
                </div>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <img
                  src="/budy-pet.png"
                  width="400"
                  height="400"
                  alt="Hero"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-primary">Características</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-foreground">
                  Accede de manera autónoma y privada, sos dueño de tus datos
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Para que Budy pueda asesorarte con la mejor precisión, tenga en cuenta consultas anteriores y
                  documentos compartidos. Buscamos lo mejor para vos
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold text-muted-foreground">Historial clínico digital</h3>
                <p className="text-muted-foreground">
                  Carga tu historial clínico e informes médicos, Budy esta para vos
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold text-muted-foreground">Canales de comunicación</h3>
                <p className="text-muted-foreground">
                  Escribinos desde nuestra web o para una mejor experiencia en la comodidad de tu WhatsApp
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold text-muted-foreground">Alertas de emergencia</h3>
                <p className="text-muted-foreground">
                  Nuestro sistema de IA detecta problemas de salud y envía alertas a tus contactos de emergencia.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold text-muted-foreground">Privacidad y seguridad</h3>
                <p className="text-muted-foreground">
                  Tus datos están protegidos en la blockchain, con acceso controlado y encriptación avanzada.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold text-muted-foreground">Seguimiento de la salud</h3>
                <p className="text-muted-foreground">
                  Monitorea tus indicadores de salud y recibe recomendaciones para mejorar tu bienestar.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold text-muted-foreground">Interoperabilidad</h3>
                <p className="text-muted-foreground">
                  Integra tus dispositivos y aplicaciones de salud para una experiencia unificada.
                </p>
              </div>
            </div>
            <div className="flex justify-center flex-col sm:flex-row items-start gap-4">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Empezar
              </Link>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Más información
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight text-foreground">
                Seguridad y privacidad de tus datos
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                La tecnología blockchain y la encriptación avanzada de Budy garantizan la confidencialidad y el control
                de tus datos médicos.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <div className="flex flex-col gap-2 items-center">
                <LockIcon className="h-14 w-14 text-primary" />
                <div>
                  <h3 className="text-lg font-bold text-foreground">Blockchain segura</h3>
                  <p className="text-muted-foreground">
                    Tus datos se almacenan de manera descentralizada y criptográfica en la blockchain, lo que los hace
                    prácticamente inaccesibles para terceros.
                  </p>
                </div>
              </div>
              <div className="flex flex-col gap-2 items-center">
                <ShieldIcon className="h-14 w-14 text-primary" />
                <div>
                  <h3 className="text-lg font-bold text-foreground">Encriptación avanzada</h3>
                  <p className="text-muted-foreground">
                    Utilizamos algoritmos de encriptación de última generación para proteger tus registros médicos y
                    garantizar su confidencialidad.
                  </p>
                </div>
              </div>
              <div className="flex flex-col gap-2 items-center">
                <KeyIcon className="h-14 w-14 text-primary" />
                <div>
                  <h3 className="text-lg font-bold text-foreground">Control de acceso</h3>
                  <p className="text-muted-foreground">
                    Tú decides quién puede acceder a tus datos médicos. Solo tú tienes el control total sobre tu
                    información.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 px-10 md:gap-16 lg:grid-cols-2">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-primary">Empieza ahora</div>
                <h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem] text-gray-700">
                  Toma el control de tu salud con Budy
                </h2>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Empezar
                </Link>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-primary">Descubre más</div>
                <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed">
                  Conoce más sobre cómo Budy está transformando la atención médica con tecnología avanzada. Descubre
                  cómo puedes mejorar tu salud y bienestar de manera segura y personalizada.
                </p>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Más información
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function KeyIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4" />
      <path d="m21 2-9.6 9.6" />
      <circle cx="7.5" cy="15.5" r="5.5" />
    </svg>
  );
}

function LockIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  );
}

function ShieldIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
    </svg>
  );
}
